### ISSUE TITLE
Overlay signal

### ISSUE THREAD

**Issue by bkargoll** [CMSAachen3B/PlottingTool#2]
Signal should be treated differently than BG in plotting tool
* __Bug__: Last sample in samples vector seems not to be drawn at all at the moment
* __Enhancement__: Allow to overlay or stack signal sample(s)
    * Include signal flag in sample struct?

**Comment by azotz** [comment]
In PlottingHelpers.h, line 125 (here: https://github.com/azotz/PlottingTool/blob/master/plottingHelpers.h#L125):

The loop over the MC histos EXCLUDES the histogram added last for the calculation of the data/MC ratio. This should be optional
